- name: Linux upgrade all by apt-get
  hosts: all
  tasks:
    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    # https://docs.ansible.com/ansible/2.9_ja/user_guide/become.html
    - name: apt-get update && upgrade
      apt:
        # update_cache: yes
        upgrade: dist
        autoremove: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
      become: yes
      register: result

    - name: Report result
      debug:
        var: result
