- name: Linux upgrade all by apt
  hosts: all
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/apt_module.html
  - name: apt-get update
    apt:
      update_cache: yes
      force_apt_get: yes
    register: result_apt-get-update
    when: ansible_system == "Linux"

  - name: apt-get upgrade all
    apt:
      upgrade: yes
      force_apt_get: yes
      allow_unauthenticated: yes
    register: result_apt-get-upgrade
    when: ansible_system == "Linux"

  - name: Report apt-get update
    debug: var=result_apt-get-update

  - name: Report apt-get upgrade
    debug: var=result_apt-get-upgrade
