- name: Are you alive
  hosts: all
  tasks:
    - name: hostname
      win_shell: hostname
      register: result_hostname
    - name: ping
      win_ping:
      register: result_ping
    - name: debug
      debug:
        var=[result_hostname.stdout_lines[0],result_ping.ping]
