- name: Are you alive
  hosts: all
  tasks:
    - name: system info
      debug:
        var: ansible_system,ansible_os_family,ansible_os_name

    - name: ping on linux
      ping:
      when: ansible_facts["system"] == "Linux"
      register: result_linux

    - name: ping on windows
      win_ping:
      when: ansible_facts["os_family"] == "Windows"
      register: result_win

    - name: report on linux
      debug:
        var: result_linux.ping
      when: result_linux.ping is defined
    
    - name: report on windows
      debug:
        var: result_win.ping
      when: result_win.ping is defined
