- name: choco install favorite apps
  hosts: all
  tasks:
  - name: install Chocolatey
    win_chocolatey:
      name: chocolatey
      state: latest
    when:
      - ansible_os_family == "Windows"
  
  - name: disable enhanced exit codes
    win_chocolatey_feature:
      name: useEnhancedExitCodes
      state: disabled
    when:
      - ansible_os_family == "Windows"
  
  - name: install packages
    win_chocolatey:
      name:
      - GoogleChrome
      - 7zip
      - vscode
      - chocolateygui
      state: latest
    when:
      - ansible_os_family == "Windows"
    register: result

  - name: report
    debug: var=result
