- name: choco upgrade all
  hosts: windows
  tasks:
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
    register: result

  - name: report
    debug: var=result
