- name: choco upgrade all
  hosts: all
  tasks:
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
    register: result
    when:
      - ansible_os_family == "Windows"
      - ansible_env.ChocolateyInstall != ""

  - name: report
    debug: var=result
