- name: choco upgrade all
  hosts: all
  tasks:
  - name: List installed packages
    win_chocolatey:
      name: all
    register: result
    when:
      - ansible_os_family == "Windows"

  - name: report
    debug: var=result
