- name: choco install favorite apps
  hosts: all
  tasks:
  - name: install packages
    win_chocolatey:
      name:
        - GoogleChrome
        - 7zip
        - vscode
        - chocolateygui
      state: present
  - name: upgrade packages
    win_chocolatey:
      name:
        - GoogleChrome
        - 7zip
        - vscode
        - chocolateygui
      state: latest
