- name: choco install favorite apps
  hosts: all
  tasks:
  - name: install Chocolatey
    win_chocolatey:
      name: chocolatey
      state: present

  - name: disable enhanced exit codes
    win_chocolatey_feature:
      name: useEnhancedExitCodes
      state: disabled

  - name: install packages
    win_chocolatey:
      name:
      - GoogleChrome
      - 7zip
      - vscode
      - chocolateygui
      state: latest
