- name: choco upgrade all
  hosts: all
  tasks:
  - name: install Chocolatey
    win_chocolatey:
      name: chocolatey
      state: latest
    when:
      - ansible_os_family == "Windows"
  
  - name: disable enhanced exit codes
    win_chocolatey_feature:
      name: useEnhancedExitCodes
      state: disabled
    when:
      - ansible_os_family == "Windows"
  
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
    register: result
    when:
      - ansible_os_family == "Windows"

  - name: report
    debug: var=result
