- name: Install Hyper-V Features
  hosts: all
  tasks:
  - name: Install Features
    win_feature:
      name:
        - Hyper-V
        - RSAT-Hyper-V-Tools
      state: present
    when:
      - ansible_os_family == "Windows"
