- name: Remove user edu as local user
  hosts: all
  tasks:
  - name: user edu absent
    win_user:
      name: edu
      state: absent
    when:
      - ansible_os_family == "Windows"
    register: result
  - name: report
    debug: var=result
