- name: Windows update and reboot if it is required
  hosts: all
  tasks:
  - name: Reboot if reboot_pending
    win_reboot:
      reboot_timeout: 1800
    when: ansible_facts["reboot_pending"]

  # https://docs.ansible.com/ansible/latest/modules/win_updates_module.html
  - name: Update windows
    win_updates:
      state: installed
      category_names: '*'
      reboot: yes
    register: result_update

  - name: Report windows update
    debug:
      var: result_update
