- name: Windows update
  hosts: all
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/win_updates_module.html
  - name: Update windows
    win_updates:
      state: installed
      reboot: no
    register: update_result
    when: ansible_os_family == "Windows"

  - name: Report windows update
    debug: var=update_result

  - name: Report reboot required
    debug:
      var: update_result.reboot_required
    when: update_result.reboot_required
  
  - name: Report reboot_pending
    debug:
      var: ansible_facts["reboot_pending"]
    when: ansible_facts["reboot_pending"]
