- name: windows update and choco upgrade
  hosts: all
  tasks:
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
    register: result_choco
    when:
      - ansible_os_family == "Windows"
      - ansible_env.ChocolateyInstall != ""

  - name: Update windows
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      reboot: yes
    register: result_update
    when: ansible_os_family == "Windows"

  - name: Report windows update
    debug: var=result_update

  - name: Report choco upgrade
    debug: var=result_choco
