- name: windows update and choco upgrade
  hosts: windows
  tasks:
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
    register: result_upgrade

  - name: Update windows
    win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      reboot: yes
    register: result_update

  - name: Report windows update
    debug: var=result_update

  - name: Report choco upgrade
    debug: var=result_upgrade
